### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by marcus-sa** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#101]
In response to all the issues around where contact should be, I've gone ahead and created an _official_ Discord server specifically for this purpose, amongst other related communication reasons.

https://discord.gg/mRFAg27

**Comment by Flarp** [comment]
How is it official? Who made it official?

Having a Discord server just makes it harder to keep track of everything, not everyone has one.

**Comment by vassudanagunta** [comment]
> How is it official? Who made it official?

this.
