### ISSUE TITLE
a mirror of this repo ?

### ISSUE THREAD

**Issue by tst2005** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#102]
Hello
Did you planned to have a mirror of this repo outside of github ?
To prevend censorship ... or anything else...

Regards,

**Comment by tst2005** [comment]
oh sorry, duplicate : https://github.com/upend/IF_MS_BUYS_GITHUB_IMMA_OUT/issues/92

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas
