### ISSUE TITLE
Adding this image to explain our situation right now

### ISSUE THREAD

**Issue by engyasin** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#103]
I think this image well convey an idea of the situation right now, so may add it to README (instead of the previous one)
actually I opened an account in GitLab and moved my repos there, but there's still some work for me here in github..

![34448051_1833306990069957_4926335739144175616_n](https://user-images.githubusercontent.com/15736151/41064030-e57282b2-69c9-11e8-8bcf-3e79f5231d48.jpg)

**Comment by unixfox** [comment]
Please consider posting this here: https://github.com/upend/IF_MS_BUYS_GITHUB_IMMA_OUT/issues/38

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas
