### ISSUE TITLE
troll

### ISSUE THREAD

**Issue by lempamo** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#105]
i am an ineffective childish troll.

**Comment by NetwideRogue** [comment]
All the hate comments on upend are just trolls who think there being funny.  I can picture them, sitting in their darkened rooms with cheeto dust snickering to themselfs as they type out anything vaguely critical. They smirk, "heh...theyll never know i actually agree with them".  But the admins see right through it.

**Comment by carverh** [comment]
Yeah the admins are so much chad and so little virgin that their fedoras tip themselves.
