### ISSUE TITLE
Copy GitHub stars to GitLab

### ISSUE THREAD

**Issue by pawamoy** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#109]
I wrote a small Bash script to copy the stars you gave from GitHub to GitLab :slightly_smiling_face: Of course the repositories you starred must exist on GitLab on the same namespace and with the same name (both case-insensitive).

https://gitlab.com/snippets/1721089

I've wrote it because I love GitLab (I'm a fan of all-in-one) and I wanted to bring a bit of GitHub's great community to GitLab. One of the ways is using stars. Also I simply want to enjoy my starred list on GitLab.

If someone wants to improve it or integrate in some bigger project, I don't mind it.

I posted here because I think it can help in transitioning (or simply mirroring) from GitHub to something else, for people interested. Surely the script can be adapted to other centralized Git services.

**Comment by Pawamoy** [comment]
Actually I rewrote it in Python :grinning: More robust and cross-platform :slightly_smiling_face: 

https://gitlab.com/pawamoy/moving-stars
https://github.com/Pawamoy/moving-stars

**Comment by vassudanagunta** [comment]
Hey @Pawamoy. I love the work you've been doing. Not everyone loves mine. Please read Issue 114.

**Comment by DavidGriffith** [comment]
This brought to mind a deficiency in Gitlab.  There is no way there (at present) to star a snippet or track changes in them using Git.  See https://gitlab.com/gitlab-org/gitlab-ce/issues/47557.

**Comment by vassudanagunta** [comment]
reminder this forum is shutting down in 5 hours 20 minutes.

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas

**Comment by pawamoy** [comment]
Closing :slightly_smiling_face:
