### ISSUE TITLE
This repo is an abuse of process

### ISSUE THREAD

**Issue by ahouse101** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#113]
Yes, I read the blurb. It's very hypocritical to attempt to silence dissent with the phrase "Please respect our wishes in our house" when you're attempting to actively run a discussion forum using software meant to host source code repositories.

I know the creators of this repository don't actually care about fairness, but given that many who use this website do, I feel it is appropriate to say this: if Microsoft's acquisition bothers you, you can always leave. Don't pollute this site with drama like this, use a proper discussion forum.

**Comment by vassudanagunta** [comment]
I totally hear you @yegortimoshenko. Thank you for saying it with kindness. Here's how I've decided to resolve this: #114.
