### ISSUE TITLE
Savannah/Savane

### ISSUE THREAD

**Issue by zafan** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#115]
There might be another option to migrate to.
**GNU Savannah/Savane** it supports:

* GIT
* Mercurial
* Bazaar
* Subversion
* CVS

It's FOSS and actually can be modified (e.g. facelift)

```"Savane is a Web-based Libre Software hosting system. It includes issue tracking (bugs, tasks, support, news and documentation), project member management by roles and individual account maintenance. "``` 
-- from [gnu savannah](https://savannah.nongnu.org/p/savane)

I didn't know where to add it - the spreadsheet is not writable.

**Comment by vassudanagunta** [comment]
@Serphentas, can you help @zafan with getting it on the spreadsheet? Do you own it?

**Comment by Serphentas** [comment]
@vassudanagunta Sure thing.

@zafan Please type your gmail address in a comment on the spreadsheet. I will grant you write access afterwards.

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas
