### ISSUE TITLE
GitHub Evacuation Center Discord

### ISSUE THREAD

**Issue by infinitetismal** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#117]
I have made a GHEC (GitHub Evacuation Center) Discord channel. If someone could make a logo for it that would be great. I hope to see you there. https://discord.gg/7CfJjDp

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas
