### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by anatolinicolae** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#120]
I am no lawyer,

but pay attention at how you use GitHub's name in the project name—they might not like this if you were not allowed by them.

If you get sued in first instance, you could be held liable for misleading people into thinking that this is a real GitHub project and they could charge you some numbers of people leaving GitHub for alternatives because of the project.

Even though, I would love to hear more from lawyers about this one...

**Comment by vassudanagunta** [comment]
The use of "GitHub" in the project name is "[fair use](https://en.wikipedia.org/wiki/Fair_use_(U.S._trademark_law))". And while GitHub itself might be able to legally delete this repo (with the attendant bad publicity), the First Amendment would prevent the courts from finding in their favor in case of a lawsuit. 

The following is [an Excerpted from Chapter 6 (Trademark, Service Mark, Trade Name and Trade Dress Protection in Cyberspace) of E-Commerce and Internet Law: A Legal Treatise With Forms, Second Edition, a 4-volume legal treatise by Ian C. Ballon (Thomson/West Publishing 2014)](http://www.laipla.net/wp-content/uploads/2014/06/Fair-Use-exc-for-LAIPLA-Spring-Seminar-June-2014.pdf):

> ### Fair Use and First Amendment Issues Involving Consumer Criticism and Gripe Sites, Blogs and Personal Homepages
> Consumer criticism sites (also called gripe sites and sometimes denominated as “sucks” sites when that appellation is applicable) are websites and blogs dedicated to complaints about a single company or multiple businesses. It is often di􏰁cult to successfully challenge one of these sites because noncommercial use of a mark is not actionable as trademark infringement, dilution or unfair competition under the Lanham Act. Where a site has commercial components, remedies may be available (to the extent of the commercial use) unless the use of a mark represents a fair use. Even if potentially actionable, an infringement or unfair competition claim may be unsuccessful if a mark owner cannot show likelihood of confusion or dilution. For example, likelihood of confusion may be di􏰁cult to establish if a site owner's antipathy for the mark owner is clear (as in the case of “sucks” sites) or the site's status as a forum for criticism or commentary is apparent.

Thanks for thinking about this.
