### ISSUE TITLE
This is retarded

### ISSUE THREAD

**Issue by rjm-codes** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#122]
Microsoft is just another company and GitHub is another free, open-source developer site. Companies will be companies and therefore no one needs to care about this movement but they do and it's completely fucking retarded.

**Comment by rjm-codes** [comment]
[This](https://github.com/MarounMaroun/IMMA_STAY_IF_MS_BUYS_GITHUB) is what y'all should be starring

**Comment by stinovlas** [comment]
You don't agree with this movement and don't worry about Microsoft acquiring GitHub. I do worry. Lots of other people do worry, too. My worries are based on long-term experience with Microsoft. Maybe those worries will come true and maybe they don't. But I don't see any reason for you to call me or anyone else retarded.

Why are you so outraged by this movement and it's supporters?

**Comment by bheywar** [comment]
howaboutno.png

>some believe deeply that the open source community needs an independent home. Some believe that the concentration of so much power in the hands of so few is antithetical not just to free and open software, but also to a free and just society. 

https://gitlab.com/upend/upend.org-content/blob/master/raison-d-etre.md

It's necessary.

**Comment by rjm-codes** [comment]
I’m not calling anyone retarded, I don’t agree with this movement. “This” refers to the movement itself, not the supporters. Go learn grammar.

**Comment by rjm-codes** [comment]
We each have our own opinions and that’s fine. Period.

**Comment by bheywar** [comment]
You "**don't agree** with it", yet you're actively shilling an opposing side.

And yeah, this is our opinion. Go support that other repo.

**Comment by rjm-codes** [comment]
And?

**Comment by stinovlas** [comment]
Indeed I'm no native speaker, but "no one needs to care about this movement but they do and it's completely fucking retarded" has a meaning that the caring itself is retarded and that caring is unseparable from the person. I still don't see why are you being so aggressive.

**Comment by bheywar** [comment]
And... What?
