### ISSUE TITLE
Already feels like home

### ISSUE THREAD

**Issue by anatolinicolae** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#19]
Our fellow friend @martenbjork is helping us move to our new home by repainting the walls with his nice-🍑looking Chrome extension that brings back the best OS ever, **Windows 😝** <sup>(1)</sup>.

Wanna feel like home? Get his extension:
https://github.com/martenbjork/github-xp

<details>
<summary>Notes</summary>
<br>
1. 🤦‍♂️  Windows XP
</details>

**Comment by mistermantas** [comment]
Well, that’s a waste of time & effort.

**Comment by anatolinicolae** [comment]
I see, maybe Microsoft is already on their way to this, right? 🤔

**Comment by mistermantas** [comment]
No, that’s the old Microsoft, they’ll probably redesign the site in an incosistent manner and add ads to like the search bar or something. *(cough) Windows 10 (cough)*

**Comment by anatolinicolae** [comment]
# Windows is not genuine
Your computer might not be running a counterfeit copy of Windows.
In order to see this comment you must activate today. [Activate Windows now.](http://fakeupdate.net/win10u/)

**Comment by mistermantas** [comment]
> Your computer might *not* be running a counterfeit copy of Windows.

Oh, is it supposed to be running a counterfeit copy? 🤔

**Comment by anatolinicolae** [comment]
🤔

**Comment by mistermantas** [comment]
Well, now that that’s done, what do you want to do now?

**Comment by vassudanagunta** [comment]
Ok guys, you've had your fun. But this place is focused on a mission. Let's not create a bunch of noise for the growing number of people following this repo. You don't joke around in the Linux or Node or Python Issue databases, do you? I mean, if you guys had a joke that would make a lot of people laugh, sure. 😜
