### ISSUE TITLE
微软是时候看一下自己有多招人嫌

### ISSUE THREAD

**Issue by aiyolo** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#2]

**Comment by vassudanagunta** [comment]
"It's time for Microsoft to look at how many people it has hired"? Can you explain further?

**Comment by maple3142** [comment]
It means "It is time for Microsoft to take a look at how annoying it is.".

**Comment by timfeirg** [comment]
is this trolling?

**Comment by vassudanagunta** [comment]
i think its venting.

**Comment by aiyolo** [comment]
don't need to take my words too seriously! part of the reason that people are unwilling to see MS purchases github lies in their different background culture，MS fails to live up to people's（or my?） expections in the recent years as a great company, though, it is changing.

**Comment by vassudanagunta** [comment]
@aiyolo shall we close this issue as it's distracting from the mission?
