### ISSUE TITLE
Provide best practices for a "placeholder" Github presence with forwarding address

### ISSUE THREAD

**Issue by vassudanagunta** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#23]
People who've been on GitHub for a long time may have a lot of external links to their GitHub profile and repos. 

For repos, for example, is there a way to delete all the code in the repo, replacing it with a forwarding address in the README, and do it in a way that doesn't blow away downstream clones?

**Comment by rdebath** [comment]
Gitlab has "push" and "pull" from remote repositories. If your host doesn't have that facility a `cron` script can do it too, with the advantage that you control how complete or out of date it is.

This allows you to continue to use github as a pure distribution system and funnel into your preferred host. With the automatic script allowing for trivial modification of the repository to, for instance, make the default branch on github "special" or only push maintenance branches to github.

Though, just changing the default branch on github would allow you to make the repo look like it just contains a README in the guthub GUI. eg: https://github.com/rdebath/test 

``` sh
#!/bin/sh
set -e
cd /home/github/putty
git fetch origin
git push -q -f git@github.com:rdebath/PuTTY.git origin/master:refs/heads/master
```

Note: This script does not need a remote for github, the remote is being specified explicitly in the command line.

**Comment by vassudanagunta** [comment]
Hey guys. I love the work you've been doing. Not everyone loves mine. Please read Issue 114.

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas
