### ISSUE TITLE
OUT

### ISSUE THREAD

**Issue by Frangte** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#27]
The purpose of this repo is to give a voice to those who wanted an independent GitHub, not one owned by any company with any business or agenda outside of serving the open source community. It is a place for such people to collaborate on options, given that GitHub is no longer independent.

If you are not such a person, this place isn't a forum for you.

It is NOT a place to debate the acquisition or the opinions of those opposed to it. It is not a place for you to try to convert people. It is certainly not a place to patronize, troll or otherwise be rude. I will enforce this without hesitation.

Please respect our wishes. You are welcome to make whatever argument you want on UpEnd's twitter (link in the README), if you really need to.

**Comment by bashrc** [comment]
Microsoft has shills. It's a long and dishonorable tradition at that company.
