### ISSUE TITLE
Add link to change.org petition

### ISSUE THREAD

**Issue by xkr47** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#3]
Add link to: https://www.change.org/p/microsoft-stop-microsoft-from-buying-github

**Comment by tay10r** [comment]
Looks like they acquired it already and are making the announcement on Monday.

https://www.bloomberg.com/news/articles/2018-06-03/microsoft-is-said-to-have-agreed-to-acquire-coding-site-github

**Comment by vassudanagunta** [comment]
Hi @xkr47. I'd normally say a change.org petition is a good idea. But the best place to sign a petition to send a message to GitHub is right here on GitHub. Each star on this repo represents the signature of actual users on this account. What can be better than that?

The good news is that this repo, created just yesterday, is now a top 10 trending repo on GitHub. Let's keep it up!

**Comment by vassudanagunta** [comment]
@tay10r, I heard 😢

But no reason to stop. We have to keep building a movement against such concentration of power... Microsoft, Facebook, Google... Not a backlash forced Google to back out of a partnership with the US Military. Can't stop. The free world depends on free people speaking up.
