### ISSUE TITLE
Just walk away

### ISSUE THREAD

**Issue by The-Humungus** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#33]
There has been too much violence, too much pain.  
None here are without sin.  
I am gravely disappointed.  
Again you have made me unleash my brand ambassadors.  
Look at what remains of your gallant repositories.  
Why? Because you're selfish! 
You hoard your feature branches. 

Now, my prisoners say 
you plan to take your repositories out of the Github.  
You sent them out this morning to find another hosting provider. 
What a puny plan!   
Look around you.   
This is the Valley of Sillicon.   
See!  
Nothing can escape! The Humungus rules the Github!  

But I have an honorable compromise.  
Just walk away. 
Give me the repositories ,the orgs, the administrator rights ,and the whole refugee camp, and I'll spare your commit histories. 

Just walk away. I will give you safe passage to Gitlab.

**Comment by vassudanagunta** [comment]
ok thanks for that.

**Comment by vassudanagunta** [comment]
I mean, like I agree with the spirt of much of what you said. But people need concrete, unbiased, well thought through recommendations right now. I can't let this turn into a crying, whining and bitching session.
