### ISSUE TITLE
The People's Art Collection

### ISSUE THREAD

**Issue by elmot** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#38]
While the topic of the repository is quite disturbing, nobody died yet because of the acquisition, and people already started to laugh on it. Let's collect here creative artifacts related to the topic. Of course, no violence, no racism, no insults etc.

**Comment by elmot** [comment]
![image](https://user-images.githubusercontent.com/5366945/40939999-093a3e32-684f-11e8-8932-54c68934fd18.png)

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/40940120-73649ba4-684f-11e8-8f90-c39d220b2f58.png)

**Comment by dkfiresky** [comment]
![40892098-ceda7c40-6789-11e8-87ac-7a4496e8e3fc](https://user-images.githubusercontent.com/2175645/40940395-4b9857cc-6850-11e8-8f8b-eaea0a99befc.jpg)

**Comment by GitSquared** [comment]
![](https://i.imgur.com/20ajD6H.jpg)

**Comment by dkfiresky** [comment]
![derxhrewsayqsa7](https://user-images.githubusercontent.com/2175645/40940402-561c2c6e-6850-11e8-8c21-0cc15d88b4d3.jpg)

**Comment by limonte** [comment]
They found quite an expensive way to restore the IE11 support:

![image](https://user-images.githubusercontent.com/6059356/40940424-64924904-6850-11e8-953f-3604b7a2ae04.png)

**Comment by GitSquared** [comment]
r/programmerhumor got some good memes on this whole thing

![](https://i.imgur.com/RGOQObq.png)

**Comment by Bystroushaak** [comment]
![](http://www.abclinuxu.cz/data/prilohy/5/0/232705-github-com-smazano-2018-06-04-3494331338925860605.png)

**Comment by dkfiresky** [comment]
![microsoftteams-image](https://user-images.githubusercontent.com/2175645/40940664-2a801d26-6851-11e8-88b5-1649a09245e3.png)

**Comment by GitSquared** [comment]
![](https://i.imgur.com/M1EZ2w9.jpg)

**Comment by unixfox** [comment]
![de17pikxuae27w6 jpg large](https://user-images.githubusercontent.com/4016501/40942172-9718f2d6-684d-11e8-8d27-58e76a80eb20.jpg)
Author: https://twitter.com/nikitonsky/status/1003593821723267072

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/40943815-2a95700e-685b-11e8-88b4-1482cec255d5.png)

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/40943823-361b957a-685b-11e8-9b9f-48459be5570e.png)

**Comment by Bystroushaak** [comment]
![](https://i.imgur.com/uJdOetI.jpg)

**Comment by Bystroushaak** [comment]
![](https://i.redd.it/75ra0bolq0211.png)

**Comment by moealmaw** [comment]
The new Github url will be https://github.msn.com/Home/Page/Default.aspx?

**Comment by sarojkh** [comment]
Source: https://twitter.com/YourAnonNews/status/1003626764378214400
![screen shot 2018-06-05 at 11 12 05 am](https://user-images.githubusercontent.com/7038624/40956686-599dc846-68b1-11e8-8d58-22190bf0c043.png)

**Comment by ParityError** [comment]
![github_fatal](https://user-images.githubusercontent.com/36368048/40957065-38388c54-6848-11e8-909b-b04315319531.png)

**Comment by elmot** [comment]
https://twitter.com/habuma/status/1003639817211555840
![image](https://user-images.githubusercontent.com/5366945/40959105-568cd2ee-68a4-11e8-8130-6a5cac6e31a7.png)

**Comment by unixfox** [comment]
https://i.redd.it/k9l6aeqvmx111.png

**Comment by elmot** [comment]
![image](https://user-images.githubusercontent.com/5366945/40963448-3bc5f5b4-68b1-11e8-8110-078f42712035.png)

**Comment by wrnice** [comment]
![byegithub](https://user-images.githubusercontent.com/18357181/40966180-11048224-68b0-11e8-869c-1b372af5b0e2.jpg)

**Comment by Bystroushaak** [comment]
![](https://pbs.twimg.com/media/De5iKREUEAAzu9b.jpg:large)

**Comment by elmot** [comment]
![image](https://user-images.githubusercontent.com/5366945/40976636-606cc1b0-68d7-11e8-888f-686de5acb601.png)

**Comment by judaschwartz** [comment]
![](https://pbs.twimg.com/media/De74HXjU0AA9cmd.jpg)
I wonder if that is going to change now?

**Comment by lieff** [comment]
![img](https://pbs.twimg.com/media/De2tsCyXcAEgvn8.jpg)

**Comment by myfingerhurt** [comment]
https://twitter.com/thegodofneet/status/1003268050483798016?s=21

**Comment by lieff** [comment]
![](https://pbs.twimg.com/media/De1fl4NXkAEFF9q.jpg)
https://twitter.com/iMilnb/status/1003563466563772417

**Comment by Bystroushaak** [comment]
![](https://i.nyx.cz/files/00/00/18/55/1855427_1f15f22a097163f4720b.png?name=Screen+Shot+2018-06-06+at+11.19.30.png)

**Comment by lieff** [comment]
![](https://pbs.twimg.com/media/De2vI7-WsAMVvup.jpg)
https://twitter.com/ChandeepKhosa/status/1003650867017539584

**Comment by geckon** [comment]
![2018-06-06_15-00_01](https://user-images.githubusercontent.com/120788/41039496-e37fe8a8-6999-11e8-8a0c-dfb3776b191a.png)

**Comment by lieff** [comment]
![](https://hsto.org/getpro/habr/comment_images/d00/37b/922/d0037b922a614cbc5f8d6983fe7d9419.jpg)

**Comment by remicaumette** [comment]
![img_1256](https://user-images.githubusercontent.com/32649258/41086662-fc5bbd42-6a3a-11e8-96d3-ed944f2e2271.JPG)

**Comment by remicaumette** [comment]
![img_1264](https://user-images.githubusercontent.com/32649258/41086693-16cba782-6a3b-11e8-84e1-86aef55b203e.JPG)

**Comment by vassudanagunta** [comment]
Please read #114.

**Comment by vassudanagunta** [comment]
Elijah,

I have no more ability than you to copy the contents of that thread. There is no “copy repo to account” facility. 

@elmot, RE your request that I help you preserve this thread:

I deeply distrust Microsoft and any company that is about amassing power rather than doing good. They had no need to acquire GitHub and take away an important independent (or so we hoped) institution.

But frankly, your thread undermined our cause, it took away from the credibility of the movement. Rather than help us articulate the real issue, it fed the impression that many have that we were a bunch of immature Microsoft bashers only doing this project because of hate rather than principle. There were many tweets about it that I don’t have time to or care to look for now.

If I weren't under siege from complaints of censorship, I would have ended it long ago. Part of me also wanted to leave it as a release valve so that people could vent their hurt feelings.  

Whatever you do, do not repost those images and associate it with UpEnd or UpEnd.org. 

vas

**Comment by vassudanagunta** [comment]
I recommend you use a Twitter account and post them there. I'm sure you'll get a lot of hearts. But again, don't associate them with UpEnd, please.

**Comment by elmot** [comment]
It is really wise, to demolish the second most commented topic in the whole repo. That is in sake of The Great Freedom, of course.

**Comment by vassudanagunta** [comment]
quantity  != quality 
popularity != validity 

The very company you are bashing 
has more people using its OS than any other, has more money than all but one or two other companies. Get my drift?

**Comment by elmot** [comment]
Nope. I do not.
Being rich != being evil
(Being rich != being goodness either)
Is it GH the very last open source code storage in the net? No, there are alternatives.
Can anybody run his own git storage? Yes, there are open-source projects, anyone including me and you can ran a copy a become that "digital refugee camp"

You try to build some society, and when the society is expressing it's opinion by posting and voting, you are just censoring it and insulting people

What are you going to achieve here?
Microsoft dissolving? Nope, it's not gonna happen
Force all the people leave GH? Nope, that is not gonna happen also.
Was GH "people-driven" before? Nope, it always was a commercial company and it always was based on closed source software.
How a thread with pictures does ruin your goals? Do those pictures break "escape routes"? 
Do they hide "evacuees status"?
Or, might be, you do have some other goals besides listed on the repo readme?
If not, why do you are going to censor those pictures?

**Comment by vassudanagunta** [comment]
![Free Speech](https://imgs.xkcd.com/comics/free_speech.png)
