### ISSUE TITLE
Stars

### ISSUE THREAD

**Issue by jorgebucaran** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#53]
Hi @vassudanagunta, interesting initiative! I just want to point that there is currently no way to indicate _lack_ of support other than not starring the repo, but we can't really count how many people refrained from starring the repo intentionally. Maybe someone can create a new repo expressing opposite views and exhort folks to star it to indicate their support (or like this issue?)

An example of this is what happened with https://github.com/dear-github/dear-github and https://github.com/thank-you-github/thank-you-github back back in the day (+2 years ago).

**Comment by MarounMaroun** [comment]
@jorgebucaran Something like [that](https://github.com/MarounMaroun/IMMA_STAY_IF_MS_BUYS_GITHUB)?

**Comment by vassudanagunta** [comment]
@jorgebucaran when I get time I'll write a longer reply, but I don't right now so this will have to do in the meantime:

You can vote opposed by simply staying on GitHub. Sadly, I'm pretty sure that the majority will. Also, you just received $7,500,000,000 votes in your favor. Isn't that enough. Please leave us be. Please do not demand *every* project support and reply to every person who doesn't like it. It's really not fair. You have plenty of places to exercise free speech.

**Comment by jorgebucaran** [comment]
Thanks, looking forward to your longer reply, I guess.

**Comment by MarounMaroun** [comment]
I don't understand why this issue is closed. It's obviously not against this repo, it only suggests creating a new one to indicate the *lack* of support.

**Comment by vassudanagunta** [comment]
So does the ACLU have to allot a room in its offices for people who don't support the ACLU ideals and mission?

**Comment by MarounMaroun** [comment]
I understand you, but I think that:

> We were the #1 project and the #4 "developer" before they deleted us. Maybe it was too embarrassing?
> 
> We have not violated any terms of service.
> 
> Is this Microsoft GitHub's commitment to an open platform for all projects? Will this repo be deleted too? Will other projects that compete with Microsoft products or challenge its dominance be on the chopping block next?

seems to be conflicting a bit with what you're trying to say.

Anyway, I do respect your repo, and wish us the best of luck.

**Comment by vassudanagunta** [comment]
On the issue of censorship, please read Issue 114.
