### ISSUE TITLE
Get over yourselves.

### ISSUE THREAD

**Issue by TheIronMarx** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#59]

**Comment by BangL** [comment]
yep.. this solid argument totally convinced me to trust microsoft. thank you.

**Comment by TheIronMarx** [comment]
Nothing could be said, nor could Microsoft do anything, that would make you do so. You'll knee-jerk yourself over to whatever subpar service is next just to get away from your antiquated, baseless vision of Microsoft.
