### ISSUE TITLE
Long-term financial solvency 

### ISSUE THREAD

**Issue by josephofiowa** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#6]
Allegedly, GitHub lost $66M in 2016. Business model changes for orgs and private repos since then imply trouble hitting profitability.

Moreover, [Developers, Developers, Developers](https://www.youtube.com/watch?v=Vhh_GeBPOhs)

**Comment by vassudanagunta** [comment]
But this is not a forum for debate. This is a place for people who wanted an independent GitHub, and will leave if it isn't. You don't go into some Node project's repo, for example, and start making comments on issues arguing that they should switch to Ruby.

The Hacker News discussions are, for example, a place to debate this. Or on Twitter. Not here.

Please be respectful of this.

**Comment by josephofiowa** [comment]
@vassudanagunta Makes sense. Thanks for alternative discussion recommendations.

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas
