### ISSUE TITLE
Alternate git implementation?

### ISSUE THREAD

**Issue by sam-irl** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#66]
Hey, all!

I've been doing a lot of thinking as to what the next steps should be, and how we can prevent any potential successor to GitHub from going the same way. So, stop me if you've heard this one before: _blockchain._

Commit data could be stored in blocks! I've mocked up a blockchain [here](https://github.com/sam-irl/gitchain.git), and if anyone wants to chip in, that'd be wonderful!

So the idea is that there is precedent to implement git in JavaScript. If repositories and commit data could be stored in blocks on the blockchain, then there would still be a centralized location for git repos, but no one company could buy it out (if they tried, they wouldn't be able to get the 51%.)

I have a simple proof-of-work right now - if anyone has any other ideas for proof-of-stake methods that would be appreciated too.

I'd love to hear thoughts on this.

**Comment by nkoehring** [comment]
The thumb-downs are pretty clear already but because you asked opinions, I might as well write some words:
An SCM on a blockchain is, just as many other blockchain ideas, not a good idea. Blockchains are not the solution to all our decentralisation problems. Blockchains are too slow, heavy, complicated and not flexible enough.

**Comment by remram44** [comment]
A blockchains stores everyone's data in a single data structure. You want everyone to have a copy of every commit ever on their machine?

If you're thinking "we could have a different blockchain per project/fork" then you are thinking about Git.

**Comment by Serphentas** [comment]
The problem we need to address is not how Git work and not how Git content is hosted. This is off topic.

**Comment by sam-irl** [comment]
closed as i’m awful?

**Comment by Serphentas** [comment]
Please handle your emotions and actually read what's been said a few posts above.

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas
