### ISSUE TITLE
Possible alternative, GitGud

### ISSUE THREAD

**Issue by RyanGannon** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#69]
https://gitgud.io/users/sign_in is a hosted GitLab, their philosophy seems to be around open-source. 
> Sapphire runs GitGud.io along with many other services. We are a user-supported open source company. Our company is designed in such a way that users are our only source of income, so we only serve them, their needs, and no other 3rd parties.
This could mean that it wouldn't scale well but worth looking into.

**Comment by Adelyne** [comment]
This is a [weird spin-off of the GamerGate, movement](http://thisisvideogames.com/gamergatewiki/index.php/GitGud) because Github was judged too "SJW".

**Comment by Serphentas** [comment]
Please see #25 to suggest this service, although this is a GitLab instance so it should be listed as a GitLab 3rd-party instance. Consider closing this issue once that's done to keep the issues list tidy.

**Comment by AkgunFatih** [comment]
since it's powered by [Gitlab](https://gitlab.com/) we should use [Gitlab](https://gitlab.com/) instead

**Comment by RyanGannon** [comment]
I see what you mean @Serphentas, will do.

**Comment by TeoTwawki** [comment]
A thing I like about gitgud: they will not bow to pressure to censor projects no matter who shows up demanding your lead dev be canned over some argument on twitter or w/e. 

[This](https://www.techdirt.com/articles/20150802/20330431831/github-nukes-repository-over-use-word-retard.shtml) will never happen at gitgud.

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas
