### ISSUE TITLE
A decentralized repository of repositories

### ISSUE THREAD

**Issue by railken** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#78]
What about leaving the "repository hosting part" to Github/Gitlab/Bitbucket/YourLovingHub, so anyone can choose where to host the code?
What about building instead a "repository" to collect them all, to rule them all. 
A sort of "index" of all repositories, from github, from bitbucket, etc.

On top of that a "social part" that we all like and all love with all the stars, issues, etc.
Once registered, a user may link or not with gitlab or his "Git-Compatible hosting" favorite.
Maybe a multiple hosts can be set.

Once created a new repository, the "default git host selected" will be used to host the actual source code/.git, while all the stars/issues/etc will be saved in this "global" repository.

This way the storage needed will be drastically reduced and could be decentralized and hosted everywhere, fully complete.
If a "x" company is lost, one can simply migrate the code to another host, preserving the community.

Like github, but with the code hosted in a server that you choose, and with the stars and issues spread all over the world.

"One Ring to rule them all, one Ring to find them,
One Ring to bring them all and in the darkness bind them"

**Comment by railken** [comment]
That's the key! Everyone is a node, but because the is no "code" hosted, everyone can be a node and have the full index/community without having PB of storage at home.

**Comment by milewski** [comment]
maybe it is something similar to: https://mastodon.social/ a decentralized social media but for coders instead

**Comment by prenex** [comment]
I support this idea. Also I would say it should be encouraged to "mirror" others repo: By default you can run a server with something like gitea, but "share" some repo publicly that is searchable by others. Do not store the stuff.

**Comment by vassudanagunta** [comment]
Hey all. I love the work you've been doing. Not everyone loves mine. Please read Issue 114.

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas
