### ISSUE TITLE
Prepare for GitHub CEO AMA on Reddit

### ISSUE THREAD

**Issue by TwinProduction** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#79]
The new CEO of GitHub, [Nat Friedman](https://en.wikipedia.org/wiki/Nat_Friedman), will be doing an AMA on Reddit in a few days. [Proof](https://www.reddit.com/r/programming/comments/8ojnah/hello_github_natfriedman/)

Also, see https://natfriedman.github.io/hello/

Prepare your questions wisely. 

---------

_Tbh, I'm already pissed at the guy. He says he's been a developer since he was **6**._

**Comment by Citizen163** [comment]
"Why are you such sniveling waste of human excrement and what original sin did humanity commit to deserve you?"

**Comment by vassudanagunta** [comment]
You're probably just venting, @Citizen163, but please, if you're going to say things like that, do that as an individual, not as part of this effort. Don't undermine the values we claim to hold and expect other people to hold.

**Comment by Citizen163** [comment]
That's not what I would write if I had a Reddit account and the time of day. I'm just echoing the questions that are most likely going to be asked, hence the quotation marks.

**Comment by vassudanagunta** [comment]
I think if there is one question that should be asked under the banner of this group, it is #88.

**Comment by nukeop** [comment]
He's the former Xamarin CEO, why would you think he's bad in any way? He's not a personification of Microsoft, he's someone that's likely to be well received by people interested in free software, that will be replaced by a corporate drone a year or two down the path.

**Comment by tobylane** [comment]
Why was a Microsoft employee chosen to lead the independent Github? The last three major acquisitions by Microsoft (Nokia, Mojang and LinkedIn) are all lead by pre-acquisition staff.

**Comment by vassudanagunta** [comment]
Hey guys. I love the work you've been doing. Not everyone loves mine. Please read Issue 114.

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas
