### ISSUE TITLE
Move to Mercurial

### ISSUE THREAD

**Issue by fn-main** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#81]
I recently migrated from GitHub to Mercurial, and I'm liking what I'm seeing. Sourcetree support, a basic TUI interface, self-hosted but very minimal on resources... If anyone else agrees let me know, but this is the path I have taken.

**Comment by cooldesigns** [comment]
It is awesome.

We can build a portal for mercurial projects which replaces github pages, or readme section. And supply index on world wide web.

**Comment by TRManderson** [comment]
Mercurial is slower than git and has a very different branching model

**Comment by lil5** [comment]
Git is a revision control system, a tool to manage your source code history.

GitHub is a hosting service for Git repositories.

So they are not the same thing: Git is the tool, GitHub is the service for projects that use Git.

https://stackoverflow.com/a/13321586

**Comment by lieff** [comment]
@fn-main I've look at mercurial too, but I do not find `--depth=1` git alternative. Do you know how to get only latest versions of files in mercurial?

**Comment by stevenvachon** [comment]
Sourcetree supports Git.

**Comment by lil5** [comment]
@stevenvachon So does GitLab, BitBucket, Sourceforge, and all the other Git hosters out there.

Here's a list for choice:
https://git.wiki.kernel.org/index.php/GitHosting

**Comment by lil5** [comment]
BitBucket supports Git

**Comment by fn-main** [comment]
Sourcetree has support for mercurial too

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas
