### ISSUE TITLE
Request for sanity / honesty from repo owners

### ISSUE THREAD

**Issue by mcmonkey4eva** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#85]
There are a fair number of issues/PR's where the posts written by users have been deleted/modified by the repo owner.

While it is reasonable to say that you don't want troll/counter-productive posts, and close/re-title them, it is not reasonable to alter or suppress the content of the posts.

How can you claim to be `a resistance movement for a free, open and people-driven internet in service of a free, open and people-driven world` (src: README.md) if you are actively censoring opposition?
Regardless of your preference or ideology, you can surely see how that action is not in alignment with stated goals?

**Comment by vassudanagunta** [comment]
When I have time I'll address this. Thank you for being respectful.

**Comment by zskovacs** [comment]
![Free](https://i.imgflip.com/2bp8qd.jpg)

**Comment by vassudanagunta** [comment]
@mcmonkey4eva There's more I'd want to say, but I don't have time. So for now [this will have to do](https://github.com/upend/IF_MS_BUYS_GITHUB_IMMA_OUT/issues/88#issuecomment-394969816). 

I think it's perfectly fair for the people in the non-violent civil rights movement to take down the Black Panther posters and the KKK posters posted in their meeting halls against their wishes.

Can't debate this anymore. I hope you get it now.

**Comment by vassudanagunta** [comment]
@neko you're not listening nor addressing my concerns, just restating your opinion. 

I have ZERO power to censor people's opinions. I am just saying they don't get to state those opinions here. This IS NOT an open forum.

Read my points at the top of #91. Tell my how you would run the ACLU? Because you are fighting for the KKK's free speech rights, does that mean you would allow them into your ACLU planning and organizing meetings? What if they wanted to add anti-Semitic or racist items to the agenda? What if when you said no, they kept interrupting the meeting with complaints that you were censoring them?

Have you ever led a group or a meeting of a large number of people not of the same mind?

**Comment by neko** [comment]
you're comparing people talking about microsoft not being the end of the world with anti-semites and racists - complete madness rly, that is why i will not be addressing your opinion.

**Comment by vassudanagunta** [comment]
My example was extreme to make it clear. The question is still valid. But the truth is that you don't have an answer.

**Comment by neko** [comment]
i will answer it to humour you.

i would allow people to critique my cause and engage in mature conversation with me about it - as opposed to outright censoring anything that does not align with my own opinions. ofc if they're disrespectful they deserve to get banned.

>Have you ever led a group or a meeting of a large number of people not of the same mind?

ye

**Comment by vassudanagunta** [comment]
Don't be condescending with this "I will humour you" line. Are you a child?

You didn't answer my question, you just made up a new one that was easy to answer.

But as I said in the other thread, it won't matter very soon.

**Comment by neko** [comment]
Don't be condescending with this "Are you a child?" line. Are you a child?

What question are you referring to? You asked at least 4 in the one paragraph, so i sort of just condensed it into "What would you do?" as it seemed like the recurring theme.

**Comment by vassudanagunta** [comment]
Please read #114.
