### ISSUE TITLE
Democratic System

### ISSUE THREAD

**Issue by Flarp** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#94]
We need some kind of democratic system for removing posts and all that junk. If the majority of the community supports it, a "benevolent" dictator isn't required.

**Comment by ferittuncer** [comment]
Okay let's leave the main concern, finding a GitHub alternative and focus on creating a democratic repository.

Outstanding idea.

**Comment by Flarp** [comment]
We can nominate alternatives and acknowledge feedback without being owned by one person

**Comment by ferittuncer** [comment]
I don't know. I think we should focus on solving the problem. I'm fine with the repository owner. But if are willing to put the necessary effort to make it happen, OK then.

**Comment by Flarp** [comment]
We could have some kind of democratic bot running, I could do that with a little help.

**Comment by vassudanagunta** [comment]
Hey guys. If you want to build a democratic system that would be amazing if you succeeded. Please read #114.

**Comment by Flarp** [comment]
Awesome, I'll look for a democratic git merge bot.
