### ISSUE TITLE
Backup copy of all conversations (issues/PRs) of this repo

### ISSUE THREAD

**Issue by limonte** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#96]
In case (when) they will delete this repo (#92), all our communication will be vanished.

As I see the solution, some service should periodically trigger GitHub API to fetch every issue and all issue comments and store them somewhere.

Does anyone have any idea how can we make a reserve copy of all conversations of this repo?

Whatwver the solution will be, it should be linked in the README, so all forks will have that information as well.

**Comment by equinox** [comment]
I'd say there's a higher chance the creator of this repo will delete content, than there is of Microsoft/GitHub deleting the repo. Funny that.

**Comment by nicholas-c** [comment]
Will just leave this here, seems like it might be useful.

https://www.amazon.co.uk/Electro-Deflecto-Unisex-Foil-Size/dp/B01I497JAM

**Comment by limonte** [comment]
If they can remove the repo from trending list without any T&C violations, what will stop them from removing it from GitHub? Seriously, @nicholas-c try to answer this question.

**Comment by nicholas-c** [comment]
Because it's simply not in their interest to do so? What would they gain from doing so? It's a pretty simple precedent really.

**Comment by limonte** [comment]
> What would they gain from doing so?

Exactly the same as they're gaining from removal this repo from trending. Prevent spreading information about GitHub issues and its alternatives. 

Fewer people will know about GitLab/BitBucket/whatnot => More people will stay here => More $$$ to M$.

**Comment by nicholas-c** [comment]
Seems legit. 

![](https://media.giphy.com/media/svb8tKSIpGfHq/giphy.gif)

**Comment by nicholas-c** [comment]
Slight sarcasm behind, if you **really** believe they'll delete the repo, just because 4k developers have starred a repo then you all seriously need a reality check. 

1) I'm sure Microsoft haven't just sent in the heavy's straight away to squash any resistance. This isn't a cold war era, Caribbean island, Cuba-esc government take over. And certainly isn't how business works.

2) In 2017, there was 24,000,000 reported active developers using Github, in essence, do you **really** believe Github, and ergo Microsoft give two craps if you stay or not? Even if you were to get 40,000 stars, and all 40,00 developers were to leave, that's still only 0.16% of the userbase... I'm sure Microsoft are shitting their pants right now at that kind of userbase loss!

3) Contributors/owners of this very repo have been deleting comments/anything that's semi resistive to their propaganda message anyway, you've got bigger issues in your own camp to worry about.

**Comment by limonte** [comment]
So, in your reality @nicholas-c, what is the reason for removing (censoring) this repo from trending? Just a simple bug in GitHub algorithms?

**Comment by tristanbettany** [comment]
I imagine you're just not as trendy as you thought you were :trollface:

**Comment by dkfiresky** [comment]
BTW, foil cap will not save you, since it increases the signals, instead of shielding 🤣

**Comment by nicholas-c** [comment]
Saul Goodman, and his crazy brother disagree.

![](https://i.pinimg.com/originals/63/7c/08/637c0823c1f63e59d6bb4dbb30dcabce.jpg) 
![](https://images.vice.com/motherboard/content-images/article/19689/1425666867375167.jpg?crop=0.9394915861081274xw:1xh;center,center&resize=1200:*)

**Comment by limonte** [comment]
Come on, guys! I'm trying to be paranoid here, stop posting foil-cap jokes and making me laugh :D

**Comment by limonte** [comment]
@nicholas-c 

> Because it's simply not in their interest to do so?

What's their interest to put Nadela Ranked to the top of https://github.com/trending/developers ? They are doing random things not because they can :smiling_imp:

**Comment by 7twin** [comment]
@limonte are you planning on removing your repos like sweetalert2 from github?

**Comment by limonte** [comment]
@7twin I don't know yet. Probably no, at least not before M$ will start censorship. Anyways, the decision on moving out isn't just mine, there are multiple collaborators in that repository and we will vote before making any decisions.

**Comment by evyatarmeged** [comment]
@dkfiresky I almost died laughing.

**Comment by dkfiresky** [comment]
@evyatarmeged great to hear that.

**Comment by AnaRobynn** [comment]
@limonte Microsoft has no power over GitHub yet... Sigh...

**Comment by vassudanagunta** [comment]
Sorry I have no tolerance for people who consider this an open forum when it isn't. But all of this won't matter very soon. I'll be making an announcement and a change to this repo so that everyone can have what they want (though they've always had that freedom).

**Comment by TwinProduction** [comment]
@vassudanagunta Like I said, it's probably a better idea to get all developers together in a discord or a slack instead of just trying to export the issues/comments. Issues by themselves have very little power -- but a group of developers do.

**Comment by vassudanagunta** [comment]
I'm a believer in self-organization and teams doing whatever works for them. That's what makes a team. What we have here is not a team and will not gel into one because of all the differences. 

So please, organize as you see fit! I will post a link to whatever you set up.

**Comment by TwinProduction** [comment]
@vassudanagunta Alright...

Well to respond to your question, you can access all the issues by using GitHub's API:

https://api.github.com/repos/upend/IF_MS_BUYS_GITHUB_IMMA_OUT/issues/events

I uploaded them to an unlisted pastebin: https://pastebin.com/uJpB1n6z

**Comment by vassudanagunta** [comment]
The comments are more important than the issue titles... they contain the work of people so far, their research, their ideas.

**Comment by TwinProduction** [comment]
It does not just contain the issues titles, it contains the issues description too.

I'm just trying to contribute here, it's better than nothing. Quite frankly, you could also just save each issue one by one as 'html page' if you're really worried about it.

If we keep using the GitHub API, instead, then you could use 

https://api.github.com/repos/upend/IF_MS_BUYS_GITHUB_IMMA_OUT/issues/96/comments

to get the comments of the #96 

https://api.github.com/repos/upend/IF_MS_BUYS_GITHUB_IMMA_OUT/issues/94/comments

to get the comments of the #94 

etc.

**Comment by vassudanagunta** [comment]
Here's why a way to export issues and comments is really important: #114.

If you guys have a solution that everyone can use, that would be awesome.

**Comment by limonte** [comment]
This is terrible: 
![image](https://user-images.githubusercontent.com/6059356/41172823-b7bfeaa4-6b5d-11e8-8c32-10137311db2f.png)

I disagree with @nicholas-c but I do respect his opinions. He spent his personal time to put his thoughts and numbers into very structured comments and you vanished all his effort.

Good luck @vassudanagunta with what you're doing. I was with you and your initiative from the very beginning, but now IMMA OUT from here.

**Comment by vassudanagunta** [comment]
@limonte See #116. I have not hit the delete button on anything on this site except those posts that disagreed with our issues with the acquisition, because this IS NOT a forum for that debate.

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas
