### ISSUE TITLE
Have a nice day!

### ISSUE THREAD

**Issue by dkfiresky** [upend/IF_MS_BUYS_GITHUB_IMMA_OUT#97]
![1024x1024](https://user-images.githubusercontent.com/2175645/41066589-fe054ff0-69ea-11e8-9d43-32fad8c422db.jpg)

**Comment by vassudanagunta** [comment]
Hello,

The GitHub Evacuation Project has moved to GitLab (not an endorsement or even a final home). Your enthusiasm and contribution is still needed. Please check out [the new project home](https://gitlab.com/upend/github), and read [the project wiki](https://gitlab.com/upend/github/evac-guide/wikis) for info to get restarted.

Thank you!

vas
